### docker-compose.yml (production)
version: '3.8'

services:
  zaphod-server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
      - ./model_cache:/app/model_cache
    environment:
      - HF_HOME=/app/model_cache
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
